### ISSUE TITLE
Font change between 0.1.1 and 0.1.3

### ISSUE THREAD

**Issue by mcanlas** [nidi3/graphviz-java#11]
Between versions `0.1.1` and `0.1.3`, the default font for node labels seems to have changed. Could you speak more to how this change was made and how we can get the `0.1.1` style rendering back?

Edit: This seems to be for PNG rendering only. When I use `.createSvg()`, I can see the label render as `Times,serif`.

**Comment by nidi3** [comment]
This was a bug in Salamander SVG renderer. It looked for the font `Times,serif` (which does not exist) instead of `Times` and then `serif`.
To get the rendering a before, use `Graph.nodeAttr().with(Font.name("Arial")).linkAttr().with(Font.name("Arial"))`.
To see what fonts are available, use `Graphviz.printFontNames()`.

**Comment by mcanlas** [comment]
Reporting in from a Mac. The font that seemed to match most closely for me was `Lucida Grande`. The font weight didn't seem correct but I think that may have to do with resolution changes. I.e. more pixels in `0.1.1` and less in `0.1.3`.

Thanks!
