### ISSUE TITLE
align nodes / clusters in graph

### ISSUE THREAD

**Issue by luckyluks** [nidi3/graphviz-java#59]
Hi there,
I am new to graphviz and this java implementation. I want to create some clusters with links between. My problem is the alingment of these clusters. 

This is what I want:
![parser](https://user-images.githubusercontent.com/27732414/39052137-45632602-44ab-11e8-8778-2e3ce8bf2901.png)

This is what I got right now:
![test1](https://user-images.githubusercontent.com/27732414/39052300-d14caad0-44ab-11e8-80fd-cf448163866a.png)

In Dot I found a simple workaround, with adding the [cosntraint=false] attribute, here in dot-code rendered at [http://webgraphviz.com/](http://webgraphviz.com/) :
```
digraph G {
	subgraph cluster_0 {
                a0 -> a1;
                a0 -> a2;
                a2 -> a3;
		label = "process #1";
	}
	subgraph cluster_1 {
		b3 -> b1 -> b2;
                b3 -> b4;
                b0 -> b1;
		label = "process #2";
	}
	a3 -> b2[constraint=false];           
}
```

I tried different ways, but didn't find an equal result to the workaround with not-constraint edges.

I found out, that if I parse my Dot-code with the constraint edge, it adds the constraint as a SimpleMutableAttribute and renders it correctly. 
I found the attribute under nodes[0].links[0].attributes:
![eclipse](https://user-images.githubusercontent.com/27732414/39052803-7bf9243a-44ad-11e8-9c24-d502f0957982.jpg)

But I didn't find a way to add this directly too.

Do I have to use invisble nodes/edges, ranks or did I miss something?

**Comment by nidi3** [comment]
Graph h = graph().with(
        graph("0").cluster().graphAttr().with(Label.of("proc 1")).with(
            node("a0").link("a1", "a2"),
            node("a2").link("a3")
        ),
        graph("1").cluster().graphAttr().with(Label.of("proc 2")).with(
            node("b3").link("b1", "b4"),
            node("b1").link("b2"),
            node("b0").link("b1")
        ),
        node("a3").link(to(node("b2")).with("constraint",false))
    );

The trick is the `to` which gives you access to the edge so that you can add attributes to it.

**Comment by luckyluks** [comment]
Danke :)

**Comment by vladtepesch** [comment]
> 
> 
> ```
> Graph h = graph().with(
>     graph("0").cluster().graphAttr().with(Label.of("proc 1")).with(
>         node("a0").link("a1", "a2"),
>         node("a2").link("a3")
>     ),
>     graph("1").cluster().graphAttr().with(Label.of("proc 2")).with(
>         node("b3").link("b1", "b4"),
>         node("b1").link("b2"),
>         node("b0").link("b1")
>     ),
>     node("a3").link(to(node("b2")).with("constraint",false))
> );
> ```
> 
> The trick is the `to` which gives you access to the edge so that you can add attributes to it.

how does this code translate into the dot language posted by the TO?

**Comment by nidi3** [comment]
I don't understand your question, what exactly is not clear?

**Comment by vladtepesch** [comment]
> 
> 
> I don't understand your question, what exactly is not clear?

May be it is my fault by misinterpreting the overall scope of the question.

I thought that I have the same problem like the OP (I want to topalign the cluster). adding `constraint=false` to the edge destroys the graph because it places the clusters at strange (unrelated) locations. But it seems that exactly this constraint-additions was the working work around for the OP.

I thought your solution somehow fixes this (you emphasized the 'to'), but your code is no dot-code. so that was my question about. How does the `to` translates into the dot language. My understanding was that your `node("a3").link(to(node("b2")).with("constraint",false))` is somehow different to `a3 -> b2[constraint=false]; `

Currently i found a work around by making my edge unconstrained and add some invisible edges that link the top-nodes of the clusters. that also is not perfect but is enough for my use case.

**Comment by nidi3** [comment]
Ah, I understand. 
`node("a3").link(to(node("b2")).with("constraint",false))` should precisely translate into `a3 -> b2[constraint=false]; `
so unfortunately it won't help with your problem.

Maybe you could ask the question in a graphviz forum?
