### ISSUE TITLE
kotlin module is not available from maven central repo

### ISSUE THREAD

**Issue by unlimitedsola** [nidi3/graphviz-java#63]

**Comment by nidi3** [comment]
Because it's not yet done 😉 
But nice to see the interest

**Comment by JLLeitschuh** [comment]
I'm also thrilled to see you are working on a Kotlin version. I'm using the Java one from Kotlin and it's amazing. I'm really interested to see what the Kotlin DSL looks like.

I work on an application that is very algorithm/graph search heavy and this library has saved me so many hours of debugging weird graph structures. Great work!

**Comment by nidi3** [comment]
I'm thinking about changing the API from immutable to mutable because for many users this seems to be confusing. When this is done, I'll do the kotlin DSL. I imagine something like this:
    
    graph("test") {
        node["color" to "red"]
        "start" - "end"
   }

So, I'll be really (mis?)using kotlin's DSL features.
What do you think?

Unfortunately, I don't have a lot of time, but seeing people's interest helps with motivation. 👍

**Comment by JLLeitschuh** [comment]
This might add overhead, but it would be nice to see a mutable DSL that returns the immutable versions of the objects.

Personally, I really like that your entire API is immutable.
It might be really helpful if you were to explicitly call that out in big bold letters in your README.

**Comment by nidi3** [comment]
Well, API design is harder that it might look like...
Maybe I can introduce kotlin DSL independently from the mutability issues.

**Comment by nidi3** [comment]
With 0.6.0, a first version of kotlin DSL is available.
Please share your thoughts 😄

**Comment by JLLeitschuh** [comment]
I'm pretty busy with a release. I'll give it a shot when I get a free moment.
