### ISSUE TITLE
Understand menssages obtained when running the simple example (libj2v8_linux_x86_64.so)

### ISSUE THREAD

**Issue by hlfernandez** [nidi3/graphviz-java#75]
Dear maintainers,

I am able to run the simple example in the README.md but I got the following messages that I do not know what to they mean:
```
16:01:56.415 [main] INFO guru.nidi.graphviz.engine.AbstractGraphvizEngine - Could not initialize guru.nidi.graphviz.engine.GraphvizCmdLineEngine
guru.nidi.graphviz.engine.GraphvizException: dot command not found
16:01:56.435 [main] INFO guru.nidi.graphviz.engine.AbstractGraphvizEngine - Starting V8 runtime...
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/hlfernandez/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
16:01:56.653 [main] INFO guru.nidi.graphviz.engine.AbstractGraphvizEngine - Started V8 runtime. Initializing graphviz...
16:01:57.158 [main] INFO guru.nidi.graphviz.engine.AbstractGraphvizEngine - Initialized graphviz.
```

As the message says, the file **_libj2v8_linux_x86_64.so_** is created in my home every time I run the code. What do this mean? Is there a way to get rid of this?

Thank you very much in advance,

Hugo.

**Comment by nidi3** [comment]
Hola Hugo

The library has 3 ways to process dot files:
- with the ‚dot‘ command if you have graphviz installed on your machine
- using javascript on a v8 engine, which is extracted in your home directory
- using javascript on java’s own javascript engine

The messages come from the first and second option.
You can customize this by using Graphviz.useEngine(). 
But usually using V8 is the best option. (no need to install anything, faster than java’s own javascript)

I created two new issues due to your mail:
https://github.com/nidi3/graphviz-java/issues/76 <https://github.com/nidi3/graphviz-java/issues/76>
https://github.com/nidi3/graphviz-java/issues/77 <https://github.com/nidi3/graphviz-java/issues/77>

thanks and cheers
nidi

**Comment by hlfernandez** [comment]
Thank you @nidi3,

I have tried using _"Graphviz.useEngine(new GraphvizJdkEngine());"_ and it works fine, without throwing any error message (although it is slower as you said)

I have seen that you have already closed the other two issues and pushed two new commits, so I am looking forward to try the 0.5.4 release with the V8 engine.

Cheers,

Hugo.

**Comment by nidi3** [comment]
I had to reopen #76 but it should still work ok.
0.5.4 is released and will be available soon.

**Comment by tamir123** [comment]
Hello @nidi3

I am getting no error while running the the simple graph on java using `Graphviz.useEngine(new GraphvizJdkEngine());`But graph is not showing or opening it just ends the process with 0.

Can you please help me

**Comment by nidi3** [comment]
hi @tamir123 
what code do you run?
normally a png file is created, but not opened/shown.
